CREATE TABLE airports (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    iata_code VARCHAR(3) UNIQUE NOT NULL,
    full_name VARCHAR(255) NOT NULL
);

CREATE INDEX idx_airport_iata_code ON airports(iata_code);

INSERT INTO airports (full_name, iata_code) VALUES
('Congonhas', 'CGH'),
('Presidente Juscelino Kubitschek', 'BSB'),
('Aeroporto Internacional Do Rio De Janeiro/Galeao', 'GIG'),
('Deputado Luis Eduardo Magalhaes', 'SSA'),
('Hercilio Luz', 'FLN'),
('Salgado Filho', 'POA'),
('Viracopos', 'VCP'),
('Guararapes - Gilberto Freyre', 'REC'),
('Afonso Pena', 'CWB'),
('Val De Cans', 'BEL'),
('Eurico De Aguiar Salles', 'VIX'),
('Santos Dumont', 'SDU'),
('Marechal Rondon', 'CGB'),
('Campo Grande', 'CGR'),
('Pinto Martins', 'FOR'),
('Macapa', 'MCP'),
('Regional De Maringa - Silvio Name Junior', 'MGF'),
('Santa Genoveva', 'GYN'),
('Ministro Victor Konder', 'NVT'),
('Eduardo Gomes', 'MAO'),
('Governador Aluizio Alves', 'NAT'),
('Porto Seguro', 'BPS'),
('Zumbi Dos Palmares', 'MCZ'),
('Brigadeiro Lysias Rodrigues', 'PMW'),
('Marechal Cunha Machado', 'SLZ'),
('Guarulhos - Governador Andre Franco Montoro', 'GRU'),
('Governador Jose Richa', 'LDB'),
('Governador Jorge Teixeira De Oliveira', 'PVH'),
('Placido De Castro', 'RBR'),
('Lauro Carneiro De Loyola', 'JOI'),
('Tenente-Coronel Aviador Cesar Bombonato', 'UDI'),
('Regional Hugo Cantergiani', 'CXJ'),
('Cataratas', 'IGU'),
('Senador Petronio Portella', 'THE'),
('Santa Maria', 'AJU'),
('Presidente Castro Pinto', 'JPA'),
('Senador Nilo Coelho', 'PNZ'),
('Tancredo Neves', 'CNF'),
('Atlas Brasil Cantanhede', 'BVB'),
('Presidente Joao Suassuna', 'CPV'),
('Maestro Wilson Fonseca', 'STM'),
('Bahia - Jorge Amado', 'IOS'),
('Orlando Bezerra De Menezes', 'JDO'),
('Prefeito Renato Moreira', 'IMP'),
('Serafin Enoss Bertaso', 'XAP'),
('Maraba', 'MAB'),
('Cruzeiro Do Sul', 'CZS'),
('Presidente Prudente', 'PPB'),
('Cabo Frio', 'CFB'),
('Fernando De Noronha', 'FEN'),
('Bauru/Arealva', 'JTC'),
('Mario Ribeiro', 'MOC'),
('Julio Belem', 'PIN'),
('Leite Lopes', 'RAO'),
('Altamira', 'ATM'),
('Pampulha - Carlos Drummond De Andrade', 'PLU'),
('Barreiras', 'BRA'),
('Coronel Altino Machado', 'GVR'),
('General Leite De Castro', 'RVD'),
('Mario De Almeida Franco', 'UBA'),
('Usiminas', 'IPN'),
('Vitoria Da Conquista', 'VDC'),
('Teixeira De Freitas', 'TXF'),
('Professor Eriberto Manoel Reino', 'SJP'),
('Presidente Joao Batista Figueiredo', 'OPS'),
('Regional Da Zona Da Mata', 'IZA'),
('Brigadeiro Camarao', 'BVH'),
('Cacoal', 'OAL'),
('Valenca', 'VAL'),
('Paulo Afonso', 'PAV'),
('Horacio De Mattos', 'LEC'),
('Tabatinga', 'TBT'),
('Itaituba', 'ITB'),
('Trombetas', 'TMT'),
('Lauro Kurtz', 'PFB'),
('Bonito', 'BYO'),
('Pelotas', 'PET'),
('Tucurui', 'TUR'),
('Joao Durval Carneiro', 'FEC'),
('Bartolomeu Lisandro', 'CAW'),
('Diomicio Freitas', 'CCM'),
('Frank Miloye Milenkovich', 'MII'),
('Municipal Francisco De Matos Pereira', 'DOU'),
('Estadual Dario Guarita', 'ARU'),
('Adalberto Mendes Da Silva', 'CAC'),
('Aeroporto Regional Plinio Alarcon', 'TLV'),
('Carajas', 'CKS'),
('Ji-Parana', 'JPR'),
('Rubem Berta', 'URG'),
('Nelson Rodrigues Guimaraes', 'CLV'),
('Maestro Marinho Franco', 'ROO'),
('Brigadeiro Cabral', 'DIW'),
('Tefe', 'TFF'),
('Corumba', 'CMG'),
('Patos De Minas', 'POJ'),
('Romeu Zema', 'AAX'),
('Carauari', 'CAF'),
('Sao Gabriel Da Cachoeira', 'SJL'),
('Barcelos', 'BAZ'),
('Eirunepe', 'ERN'),
('Coari', 'CIZ'),
('Francisco Correa Da Cruz', 'HUA'),
('Manicore', 'MNX'),
('Labrea', 'LBR'),
('Araguaina', 'AUX'),
('Professor Urbano Ernesto Stumpf', 'SJK'),
('Aeroporto De Jaguaruna', 'JJG'),
('Major Brigadeiro Trompowsky', 'VAG'),
('Correia Pinto', 'LLA'),
('Prefeito Doutor Joao Silva Filho', 'PHB'),
('Sorriso', 'SMT'),
('Ponta Grossa', 'PGZ'),
('Barra Do Garcas', 'BPG'),
('Santo Angelo', 'GEL'),
('Jericoacara', 'JJD'),
('Redencao', 'RDC'),
('Macae', 'MEA'),
('Ourilandia Do Norte', 'OUN'),
('Bartolomeu De Gusmao', 'AQA'),
('Monte Dourado', 'MME'),
('Conceicao Do Araguaia', 'CFF'),
('Brigadeiro Lysias Augusto Rodrigues', 'GRP'),
('Deputado Benedito Santiago', 'AFL'),
('Miami', 'MIA'),
('New York', 'JFK'),
('Toronto', 'YYZ'),
('Madrid', 'MAD'),
('Paris', 'CDG'),
('Bogota', 'BOG'),
('Buenos Aires', 'EZE'),
('Buenos Aires/Aeroparque', 'AEP'),
('Roma', 'FCO'),
('Sao Domingo/De Las Americas', 'SDQ'),
('Luxemburgo', 'LUX'),
('Washington/Dulles Intl', 'IAD'),
('Maldonado-Uruguai', 'PDP'),
('Cancun/Intl', 'CUN'),
('Lisboa', 'LIS'),
('Porto', 'OPO'),
('Cabo Verde', 'RAI'),
('Ilha Do Sal', 'SID'),
('Hamad', 'DOH'),
('Casablanca', 'CMN'),
('Johannesburg', 'JNB'),
('Barcelona', 'BCN'),
('Zurique', 'ZRH'),
('Quito', 'UIO'),
('Fort Lauderdale', 'FLL'),
('Orlando', 'MCO'),
('Caiena', 'CAY'),
('Londres', 'LHR'),
('Viru Viru', 'VVI'),
('Frankfurt', 'FRA'),
('Panama', 'PTY'),
('Detroit', 'DTW'),
('Atlanta/Intl', 'ATL'),
('Munchen', 'MUC'),
('Luanda', 'LAD'),
('Ab Dhabi International', 'AUH'),
('Intl Bole Airport', 'ADD'),
('Rosario', 'ROS'),
('Zandery', 'PBM'),
('Assuncao', 'ASU'),
('Mendoza', 'MDZ'),
('Montevideu', 'MVD'),
('Cordoba', 'COR'),
('Aruba', 'AUA'),
('Caracas/Intl', 'CCS'),
('Bridgetown/Grantley Adams', 'BGI'),
('Punta Cana', 'PUJ'),
('Santiago Do Chile', 'SCL'),
('Curacao', 'CUR'),
('Milao', 'MXP'),
('Amsterdam', 'AMS'),
('Cidade Del Este', 'AGT'),
('Lima', 'LIM'),
('Istanbul/Ataturk', 'ISL'),
('Dubai International', 'DXB'),
('Newark / Intl Nj', 'EWR'),
('Chicago', 'ORD'),
('Cheddi Jagan Intl', 'GEO'),
('Aeroporto Internacional Lome-Tokoin', 'LFW'),
('La Romana', 'LRM'),
('Cochabamba', 'CBB'),
('Charlotte Douglas Intl', 'CLT'),
('Los Angeles', 'LAX'),
('Dallas/Fort Worth', 'DFW'),
('Mexico', 'MEX'),
('Houston', 'IAH');